org: jorgeleandro
service: api-usuarios

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_TOKEN_ACCESO: t_token_acceso

functions:
  # api-usuarios (Python)
  CrearUsuario:
    handler: CrearUsuario.lambda_handler
    events:
      - http:
          path: /usuario/crear
          method: post
          cors: true
          integration: lambda
          
  LoginUsuario:
    handler: LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuario/login
          method: post
          cors: true
          integration: lambda
          
  ValidarToken:
    handler: ValidarToken.lambda_handler
    events:
      - http:
          path: /usuario/validar
          method: post
          cors: true
          integration: lambda
