org: jorgeleandro
service: api-peliculas

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_CINES: t_cines
    TABLE_NAME_CARTELERA: t_cartelera
    TABLE_NAME_PELICULAS: t_peliculas

functions:
  AddMovie:
    handler: Addmovie.addMovie
    events:
      - http:
          path: /pelicula/agregar
          method: post
          cors: true
          integration: lambda

  UpdateMovie:
    handler: Updatemovie.updateMovie
    events:
      - http:
          path: /pelicula/actualizar
          method: put
          cors: true
          integration: lambda

  DeleteMovie:
    handler: Deletemovie.deleteMovie
    events:
      - http:
          path: /pelicula/eliminar
          method: delete
          cors: true
          integration: lambda
    
  Cartelera:
    handler: Cartelera.cartelera
    events:
      - http:
          path: /pelicula/{cinema_id}
          method: get
          cors: true
          integration: lambda