org: jorgeleandro
service: api-reserva

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_CINES: t_cines
    TABLE_NAME_CARTELERA: t_cartelera
    TABLE_NAME_PELICULAS: t_peliculas
    TABLE_NAME_PROYECCIONES: t_proyecciones

functions:
  # api-reserva (Node.js)
  ReserveSeats:
    handler: ReserveSeats.reservarAsientos
    events:
      - http:
          path: /pelicula/reservar
          method: post
          cors: true
          integration: lambda