org: jorgeleandro
service: api-cine

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_CINES: t_cines

functions:
  # api-cine (Python)
  AddCine:
    handler: AddCine.lambda_handler
    events:
      - http:
          path: /cine/agregar
          method: post
          cors: true
          integration: lambda
          

  DeleteCine:
    handler: DeleteCine.lambda_handler
    events:
      - http:
          path: /cine/eliminar
          method: delete
          cors: true
          integration: lambda

  GetCineDetails:
    handler: GetCineDetails.lambda_handler
    events:
      - http:
          path: /cine/consultar
          method: get
          cors: true
          integration: lambda

  ListAllCines:
    handler: ListAllCines.lambda_handler
    events:
      - http:
          path: /cine/listar
          method: get
          cors: true
          integration: lambda
  
  UpdateCine:
    handler: UpdateCine.lambda_handler
    events:
      - http:
          path: /cine/actualizar
          method: put
          cors: true
          integration: lambda