org: jorgeleandro
service: backend-cine

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_CINES: t_cines
    TABLE_NAME_CARTELERA: t_cartelera
    TABLE_NAME_PELICULAS: t_peliculas
    TABLE_NAME_PROYECCIONES: t_proyecciones
    TABLE_NAME_VISITAS: t_visitas
    TABLE_NAME_TOKEN_ACCESO: t_token_acceso

resources:
  Resources:
    # Tabla de Usuarios
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_USUARIOS}
        AttributeDefinitions:
          - AttributeName: "user_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "user_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Cines
    CinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CINES}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "district"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "district"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Cartelera
    CarteleraTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CARTELERA}
        AttributeDefinitions:
          - AttributeName: "movie_id"
            AttributeType: "S"
          - AttributeName: "cinema_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "movie_id"
            KeyType: "HASH"
          - AttributeName: "cinema_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Películas
    PeliculasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PELICULAS}
        AttributeDefinitions:
          - AttributeName: "movie_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "movie_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Proyecciones
    ProyeccionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PROYECCIONES}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "show_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "show_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Visitas
    VisitasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_VISITAS}
        AttributeDefinitions:
          - AttributeName: "visita_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "visita_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Token de Acceso
    TokenAccesoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_TOKEN_ACCESO}
        AttributeDefinitions:
          - AttributeName: "token"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "token"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST