org: jorgeleandro
service: api-visitas

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 29
  region: us-east-1
  iam:
    role: arn:aws:iam::880764721962:role/LabRole
  environment:
    TABLE_NAME_USUARIOS: t_usuarios
    TABLE_NAME_VISITAS: t_visitas

functions: 
  #api-visitas (Node.js)
  GetHistorialVisita:
      handler: GetHistorialVisita.getHistorialVisita
      events:
        - http:
            path: /visitas/historial
            method: get
            cors: true
            integration: lambda

  GetVisitaEspecifica:
    handler: GetVisitaEspecifica.GetVisitaEspecifica
    events:
      - http:
          path: /visitas/detalle
          method: get
          cors: true
          integration: lambda

  VisitaPorFecha:
    handler: CompraFecha.compraFecha
    events:
      - http:
          path: /visitas/filtrar
          method: get
          cors: true
          integration: lambda