org: jorgeleandro
service: listado-peliculas

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::606646193182:role/LabRole
  environment:
    TABLE_NAME_PELICULAS: ${sls:stage}-t_peliculas
    TABLE_NAME_CARTELERA: ${sls:stage}-t_cartelera
    TABLE_NAME_FUNCIONES: ${sls:stage}-t_funciones

functions:
  listarPeliculas:
    handler: listarPeliculas.listarPeliculas
    events:
      - http:
          path: /pelicula/listar
          method: get
          cors: true
          integration: lambda

  consultarCinesPorPelicula:
    handler: consultarCinesPorPelicula.consultarCinesPorPelicula
    events:
      - http:
          path: /pelicula/cines
          method: get
          cors: true
          integration: lambda

  consultarHorariosPorCineYPelicula:
    handler: consultarHorariosPorCineYPelicula.consultarHorariosPorCineYPelicula
    events:
      - http:
          path: /pelicula/horarios
          method: get
          cors: true
          integration: lambda

  consultarDisponibilidadDeAsientos:
    handler: consultarDisponibilidadDeAsientos.consultarDisponibilidadDeAsientos
    events:
      - http:
          path: /pelicula/asientos
          method: get
          cors: true
          integration: lambda

  reservarAsientos:
    handler: reservarAsientos.reservarAsientos
    events:
      - http:
          path: /pelicula/reservar
          method: post
          cors: true
          integration: lambda

  cancelarReservaDeAsientos:
    handler: cancelarReservaDeAsientos.cancelarReservaDeAsientos
    events:
      - http:
          path: /pelicula/cancelar
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    # Tabla de Películas
    PeliculasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PELICULAS}
        AttributeDefinitions:
          - AttributeName: "movie_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "movie_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Cartelera
    CarteleraTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CARTELERA}
        AttributeDefinitions:
          - AttributeName: "movie_id"
            AttributeType: "S"
          - AttributeName: "cinema_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "movie_id"
            KeyType: "HASH"
          - AttributeName: "cinema_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: "movie-index"
            KeySchema:
              - AttributeName: "movie_id"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"

    # Tabla de Funciones
    FuncionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_FUNCIONES}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "show_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "show_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
