org: jorgeleandro
service: api-proyecciones

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::606646193182:role/LabRole
  environment:
    TABLE_NAME_PROYECCIONES: ${sls:stage}-t_proyecciones
    TABLE_NAME_USUARIOS: ${sls:stage}-t_usuarios

functions:
  # Función para agregar una función
  addProyection:
    handler: addProyection.lambda_handler
    events:
      - http:
          path: /proyection/agregar
          method: post
          cors: true
          integration: lambda

  # Función para actualizar una función
  updateProyection:
    handler: updateProyection.lambda_handler
    events:
      - http:
          path: /proyection/actualizar
          method: put
          cors: true
          integration: lambda

  # Función para eliminar una función
  deleteProyection:
    handler: deleteProyection.lambda_handler
    events:
      - http:
          path: /proyection/eliminar
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    # Tabla de proyecciones de pelicula de Cine
    ProyectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PROYECCIONES}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "show_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "show_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Usuarios (para validar permisos)
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_USUARIOS}
        AttributeDefinitions:
          - AttributeName: "user_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "user_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
