org: jorgeleandro
service: api-cine

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::606646193182:role/LabRole
  environment:
    TABLE_NAME_CINES: ${sls:stage}-t_cines
    TABLE_NAME_USUARIOS: ${sls:stage}-t_usuarios
    TABLE_NAME_CARTELERA: ${sls:stage}-t_cartelera

functions:
  # Función para agregar un cine
  addCinema:
    handler: addCinema.lambda_handler
    events:
      - http:
          path: /cine/agregar
          method: post
          cors: true
          integration: lambda

  # Función para eliminar un cine
  deleteCinema:
    handler: deleteCinema.lambda_handler
    events:
      - http:
          path: /cine/eliminar
          method: delete
          cors: true
          integration: lambda

  # Función para consultar un cine específico
  getCinema:
    handler: getCinema.lambda_handler
    events:
      - http:
          path: /cine/consultar
          method: get
          cors: true
          integration: lambda

  # Función para listar todos los cines
  listCinemas:
    handler: listCinemas.lambda_handler
    events:
      - http:
          path: /cine/listar
          method: get
          cors: true
          integration: lambda

  # Función para consultar la cartelera de un cine específico
  getCinemaSchedule:
    handler: getCinemaSchedule.lambda_handler
    events:
      - http:
          path: /cartelera/consultar
          method: get
          cors: true
          integration: lambda

  # Función para actualizar la información de un cine
  updateCinema:
    handler: updateCinema.lambda_handler
    events:
      - http:
          path: /cine/actualizar
          method: put
          cors: true
          integration: lambda

resources:
  Resources:
    # Tabla de Cines
    CinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CINES}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "district"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "district"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Usuarios
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_USUARIOS}
        AttributeDefinitions:
          - AttributeName: "user_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "user_id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    # Tabla de Cartelera
    CarteleraTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_CARTELERA}
        AttributeDefinitions:
          - AttributeName: "cinema_id"
            AttributeType: "S"
          - AttributeName: "movie_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "cinema_id"
            KeyType: "HASH"
          - AttributeName: "movie_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
